// <auto-generated />
namespace Skyline.DataMiner.Scripting
{
	using System.ComponentModel;

	public static class FleParameters
	{
		/// <summary>PID: 9990990 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fleinterappreceive_9990990 = 9990990;
		/// <summary>PID: 9990990 | Type: read</summary>
		public const int fleinterappreceive = 9990990;
		/// <summary>PID: 9990991 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int fleinterappreturn_9990991 = 9990991;
		/// <summary>PID: 9990991 | Type: read</summary>
		public const int fleinterappreturn = 9990991;
		public class Write
		{
			/// <summary>PID: 9991158 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int fleincomingflowstableexpectedrxbitrate_9991158 = 9991158;
			/// <summary>PID: 9991158 | Type: write</summary>
			public const int fleincomingflowstableexpectedrxbitrate = 9991158;
			/// <summary>PID: 9991258 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int fleoutgoingflowstableexpectedtxbitrate_9991258 = 9991258;
			/// <summary>PID: 9991258 | Type: write</summary>
			public const int fleoutgoingflowstableexpectedtxbitrate = 9991258;
		}
		public class Fleinterfacesoverviewtable
		{
			/// <summary>PID: 9991000</summary>
			public const int tablePid = 9991000;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 9991001</summary>
			public const int indexColumnPid = 9991001;
			public class Pid
			{
				/// <summary>PID: 9991001 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableindex_9991001 = 9991001;
				/// <summary>PID: 9991001 | Type: read</summary>
				public const int fleinterfacesoverviewtableindex = 9991001;
				/// <summary>PID: 9991002 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledescription_9991002 = 9991002;
				/// <summary>PID: 9991002 | Type: read</summary>
				public const int fleinterfacesoverviewtabledescription = 9991002;
				/// <summary>PID: 9991003 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletype_9991003 = 9991003;
				/// <summary>PID: 9991003 | Type: read</summary>
				public const int fleinterfacesoverviewtabletype = 9991003;
				/// <summary>PID: 9991004 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableadminstatus_9991004 = 9991004;
				/// <summary>PID: 9991004 | Type: read</summary>
				public const int fleinterfacesoverviewtableadminstatus = 9991004;
				/// <summary>PID: 9991005 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableoperstatus_9991005 = 9991005;
				/// <summary>PID: 9991005 | Type: read</summary>
				public const int fleinterfacesoverviewtableoperstatus = 9991005;
				/// <summary>PID: 9991006 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledisplaykey_9991006 = 9991006;
				/// <summary>PID: 9991006 | Type: read</summary>
				public const int fleinterfacesoverviewtabledisplaykey = 9991006;
				/// <summary>PID: 9991007 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxbitrate_9991007 = 9991007;
				/// <summary>PID: 9991007 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxbitrate = 9991007;
				/// <summary>PID: 9991008 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxflows_9991008 = 9991008;
				/// <summary>PID: 9991008 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxflows = 9991008;
				/// <summary>PID: 9991009 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxbitrate_9991009 = 9991009;
				/// <summary>PID: 9991009 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxbitrate = 9991009;
				/// <summary>PID: 9991010 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxflows_9991010 = 9991010;
				/// <summary>PID: 9991010 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxflows = 9991010;
				/// <summary>PID: 9991011 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxutilization_9991011 = 9991011;
				/// <summary>PID: 9991011 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxutilization = 9991011;
				/// <summary>PID: 9991012 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxutilization_9991012 = 9991012;
				/// <summary>PID: 9991012 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxutilization = 9991012;
				/// <summary>PID: 9991013 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitrate_9991013 = 9991013;
				/// <summary>PID: 9991013 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitrate = 9991013;
				/// <summary>PID: 9991014 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus_9991014 = 9991014;
				/// <summary>PID: 9991014 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus = 9991014;
				/// <summary>PID: 9991015 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflows_9991015 = 9991015;
				/// <summary>PID: 9991015 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflows = 9991015;
				/// <summary>PID: 9991016 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus_9991016 = 9991016;
				/// <summary>PID: 9991016 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus = 9991016;
				/// <summary>PID: 9991017 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitrate_9991017 = 9991017;
				/// <summary>PID: 9991017 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitrate = 9991017;
				/// <summary>PID: 9991018 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus_9991018 = 9991018;
				/// <summary>PID: 9991018 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus = 9991018;
				/// <summary>PID: 9991019 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflows_9991019 = 9991019;
				/// <summary>PID: 9991019 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflows = 9991019;
				/// <summary>PID: 9991020 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus_9991020 = 9991020;
				/// <summary>PID: 9991020 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus = 9991020;
				/// <summary>PID: 9991021 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledcfinterfaceid_9991021 = 9991021;
				/// <summary>PID: 9991021 | Type: read</summary>
				public const int fleinterfacesoverviewtabledcfinterfaceid = 9991021;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableindex_9991001 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleinterfacesoverviewtableindex = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledescription_9991002 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleinterfacesoverviewtabledescription = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletype_9991003 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleinterfacesoverviewtabletype = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableadminstatus_9991004 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleinterfacesoverviewtableadminstatus = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableoperstatus_9991005 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleinterfacesoverviewtableoperstatus = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledisplaykey_9991006 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleinterfacesoverviewtabledisplaykey = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxbitrate_9991007 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxflows_9991008 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxflows = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxbitrate_9991009 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxbitrate = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxflows_9991010 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxflows = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxutilization_9991011 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxutilization = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxutilization_9991012 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxutilization = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitrate_9991013 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitrate = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus_9991014 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus = 13;
				/// <summary>IDX: 14 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflows_9991015 = 14;
				/// <summary>IDX: 14 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflows = 14;
				/// <summary>IDX: 15 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus_9991016 = 15;
				/// <summary>IDX: 15 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus = 15;
				/// <summary>IDX: 16 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitrate_9991017 = 16;
				/// <summary>IDX: 16 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitrate = 16;
				/// <summary>IDX: 17 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus_9991018 = 17;
				/// <summary>IDX: 17 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus = 17;
				/// <summary>IDX: 18 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflows_9991019 = 18;
				/// <summary>IDX: 18 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflows = 18;
				/// <summary>IDX: 19 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus_9991020 = 19;
				/// <summary>IDX: 19 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus = 19;
				/// <summary>IDX: 20 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledcfinterfaceid_9991021 = 20;
				/// <summary>IDX: 20 | Type: read</summary>
				public const int fleinterfacesoverviewtabledcfinterfaceid = 20;
			}
		}
		public class Fleincomingflowstable
		{
			/// <summary>PID: 9991100</summary>
			public const int tablePid = 9991100;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 9991101</summary>
			public const int indexColumnPid = 9991101;
			public class Pid
			{
				/// <summary>PID: 9991101 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableinstance_9991101 = 9991101;
				/// <summary>PID: 9991101 | Type: read</summary>
				public const int fleincomingflowstableinstance = 9991101;
				/// <summary>PID: 9991102 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationip_9991102 = 9991102;
				/// <summary>PID: 9991102 | Type: read</summary>
				public const int fleincomingflowstabledestinationip = 9991102;
				/// <summary>PID: 9991103 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationport_9991103 = 9991103;
				/// <summary>PID: 9991103 | Type: read</summary>
				public const int fleincomingflowstabledestinationport = 9991103;
				/// <summary>PID: 9991104 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablesourceip_9991104 = 9991104;
				/// <summary>PID: 9991104 | Type: read</summary>
				public const int fleincomingflowstablesourceip = 9991104;
				/// <summary>PID: 9991105 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableincominginterface_9991105 = 9991105;
				/// <summary>PID: 9991105 | Type: read</summary>
				public const int fleincomingflowstableincominginterface = 9991105;
				/// <summary>PID: 9991106 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabletransporttype_9991106 = 9991106;
				/// <summary>PID: 9991106 | Type: read</summary>
				public const int fleincomingflowstabletransporttype = 9991106;
				/// <summary>PID: 9991107 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablerxbitrate_9991107 = 9991107;
				/// <summary>PID: 9991107 | Type: read</summary>
				public const int fleincomingflowstablerxbitrate = 9991107;
				/// <summary>PID: 9991108 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitrate_9991108 = 9991108;
				/// <summary>PID: 9991108 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitrate = 9991108;
				/// <summary>PID: 9991109 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitratestatus_9991109 = 9991109;
				/// <summary>PID: 9991109 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitratestatus = 9991109;
				/// <summary>PID: 9991110 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelabel_9991110 = 9991110;
				/// <summary>PID: 9991110 | Type: read</summary>
				public const int fleincomingflowstablelabel = 9991110;
				/// <summary>PID: 9991111 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablefkoutgoing_9991111 = 9991111;
				/// <summary>PID: 9991111 | Type: read</summary>
				public const int fleincomingflowstablefkoutgoing = 9991111;
				/// <summary>PID: 9991112 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelinkedflow_9991112 = 9991112;
				/// <summary>PID: 9991112 | Type: read</summary>
				public const int fleincomingflowstablelinkedflow = 9991112;
				/// <summary>PID: 9991113 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableflowowner_9991113 = 9991113;
				/// <summary>PID: 9991113 | Type: read</summary>
				public const int fleincomingflowstableflowowner = 9991113;
				/// <summary>PID: 9991114 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablepresent_9991114 = 9991114;
				/// <summary>PID: 9991114 | Type: read</summary>
				public const int fleincomingflowstablepresent = 9991114;
				public class Write
				{
					/// <summary>PID: 9991165 | Type: write</summary>
					[EditorBrowsable(EditorBrowsableState.Never)]
					public const int fleincomingflowstabledelete_9991165 = 9991165;
					/// <summary>PID: 9991165 | Type: write</summary>
					public const int fleincomingflowstabledelete = 9991165;
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableinstance_9991101 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleincomingflowstableinstance = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationip_9991102 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleincomingflowstabledestinationip = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationport_9991103 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleincomingflowstabledestinationport = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablesourceip_9991104 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleincomingflowstablesourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableincominginterface_9991105 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleincomingflowstableincominginterface = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabletransporttype_9991106 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleincomingflowstabletransporttype = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablerxbitrate_9991107 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleincomingflowstablerxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitrate_9991108 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitrate = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitratestatus_9991109 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitratestatus = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelabel_9991110 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleincomingflowstablelabel = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablefkoutgoing_9991111 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleincomingflowstablefkoutgoing = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelinkedflow_9991112 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleincomingflowstablelinkedflow = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableflowowner_9991113 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleincomingflowstableflowowner = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablepresent_9991114 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleincomingflowstablepresent = 13;
			}
		}
		public class Fleoutgoingflowstable
		{
			/// <summary>PID: 9991200</summary>
			public const int tablePid = 9991200;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 9991201</summary>
			public const int indexColumnPid = 9991201;
			public class Pid
			{
				/// <summary>PID: 9991201 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableinstance_9991201 = 9991201;
				/// <summary>PID: 9991201 | Type: read</summary>
				public const int fleoutgoingflowstableinstance = 9991201;
				/// <summary>PID: 9991202 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationip_9991202 = 9991202;
				/// <summary>PID: 9991202 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationip = 9991202;
				/// <summary>PID: 9991203 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationport_9991203 = 9991203;
				/// <summary>PID: 9991203 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationport = 9991203;
				/// <summary>PID: 9991204 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablesourceip_9991204 = 9991204;
				/// <summary>PID: 9991204 | Type: read</summary>
				public const int fleoutgoingflowstablesourceip = 9991204;
				/// <summary>PID: 9991205 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableoutgoinginterface_9991205 = 9991205;
				/// <summary>PID: 9991205 | Type: read</summary>
				public const int fleoutgoingflowstableoutgoinginterface = 9991205;
				/// <summary>PID: 9991206 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletransporttype_9991206 = 9991206;
				/// <summary>PID: 9991206 | Type: read</summary>
				public const int fleoutgoingflowstabletransporttype = 9991206;
				/// <summary>PID: 9991207 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletxbitrate_9991207 = 9991207;
				/// <summary>PID: 9991207 | Type: read</summary>
				public const int fleoutgoingflowstabletxbitrate = 9991207;
				/// <summary>PID: 9991208 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitrate_9991208 = 9991208;
				/// <summary>PID: 9991208 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitrate = 9991208;
				/// <summary>PID: 9991209 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitratestatus_9991209 = 9991209;
				/// <summary>PID: 9991209 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitratestatus = 9991209;
				/// <summary>PID: 9991210 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelabel_9991210 = 9991210;
				/// <summary>PID: 9991210 | Type: read</summary>
				public const int fleoutgoingflowstablelabel = 9991210;
				/// <summary>PID: 9991211 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablefkincoming_9991211 = 9991211;
				/// <summary>PID: 9991211 | Type: read</summary>
				public const int fleoutgoingflowstablefkincoming = 9991211;
				/// <summary>PID: 9991212 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelinkedflow_9991212 = 9991212;
				/// <summary>PID: 9991212 | Type: read</summary>
				public const int fleoutgoingflowstablelinkedflow = 9991212;
				/// <summary>PID: 9991213 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableflowowner_9991213 = 9991213;
				/// <summary>PID: 9991213 | Type: read</summary>
				public const int fleoutgoingflowstableflowowner = 9991213;
				/// <summary>PID: 9991214 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablepresent_9991214 = 9991214;
				/// <summary>PID: 9991214 | Type: read</summary>
				public const int fleoutgoingflowstablepresent = 9991214;
				public class Write
				{
					/// <summary>PID: 9991265 | Type: write</summary>
					[EditorBrowsable(EditorBrowsableState.Never)]
					public const int fleoutgoingflowstabledelete_9991265 = 9991265;
					/// <summary>PID: 9991265 | Type: write</summary>
					public const int fleoutgoingflowstabledelete = 9991265;
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableinstance_9991201 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleoutgoingflowstableinstance = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationip_9991202 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationip = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationport_9991203 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationport = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablesourceip_9991204 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleoutgoingflowstablesourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableoutgoinginterface_9991205 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleoutgoingflowstableoutgoinginterface = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletransporttype_9991206 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleoutgoingflowstabletransporttype = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletxbitrate_9991207 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleoutgoingflowstabletxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitrate_9991208 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitrate = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitratestatus_9991209 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitratestatus = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelabel_9991210 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleoutgoingflowstablelabel = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablefkincoming_9991211 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleoutgoingflowstablefkincoming = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelinkedflow_9991212 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleoutgoingflowstablelinkedflow = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableflowowner_9991213 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleoutgoingflowstableflowowner = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablepresent_9991214 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleoutgoingflowstablepresent = 13;
			}
		}
		public class Fleprovisionedflowstable
		{
			/// <summary>PID: 9991300</summary>
			public const int tablePid = 9991300;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 9991301</summary>
			public const int indexColumnPid = 9991301;
			public class Pid
			{
				/// <summary>PID: 9991301 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableid_9991301 = 9991301;
				/// <summary>PID: 9991301 | Type: read</summary>
				public const int fleprovisionedflowstableid = 9991301;
				/// <summary>PID: 9991302 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablesourceid_9991302 = 9991302;
				/// <summary>PID: 9991302 | Type: read</summary>
				public const int fleprovisionedflowstablesourceid = 9991302;
				/// <summary>PID: 9991303 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationid_9991303 = 9991303;
				/// <summary>PID: 9991303 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationid = 9991303;
				/// <summary>PID: 9991304 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableincomingdcfinterfaceid_9991304 = 9991304;
				/// <summary>PID: 9991304 | Type: read</summary>
				public const int fleprovisionedflowstableincomingdcfinterfaceid = 9991304;
				/// <summary>PID: 9991305 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableincomingdcfinterfacedynamiclink_9991305 = 9991305;
				/// <summary>PID: 9991305 | Type: read</summary>
				public const int fleprovisionedflowstableincomingdcfinterfacedynamiclink = 9991305;
				/// <summary>PID: 9991306 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoutgoingdcfinterfaceid_9991306 = 9991306;
				/// <summary>PID: 9991306 | Type: read</summary>
				public const int fleprovisionedflowstableoutgoingdcfinterfaceid = 9991306;
				/// <summary>PID: 9991307 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoutgoingdcfinterfacedynamiclink_9991307 = 9991307;
				/// <summary>PID: 9991307 | Type: read</summary>
				public const int fleprovisionedflowstableoutgoingdcfinterfacedynamiclink = 9991307;
				/// <summary>PID: 9991308 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoptionalsourceidentifier_9991308 = 9991308;
				/// <summary>PID: 9991308 | Type: read</summary>
				public const int fleprovisionedflowstableoptionalsourceidentifier = 9991308;
				/// <summary>PID: 9991309 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoptionaldestinationidentifier_9991309 = 9991309;
				/// <summary>PID: 9991309 | Type: read</summary>
				public const int fleprovisionedflowstableoptionaldestinationidentifier = 9991309;
				/// <summary>PID: 9991310 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationip_9991310 = 9991310;
				/// <summary>PID: 9991310 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationip = 9991310;
				/// <summary>PID: 9991311 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationport_9991311 = 9991311;
				/// <summary>PID: 9991311 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationport = 9991311;
				/// <summary>PID: 9991312 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablesourceip_9991312 = 9991312;
				/// <summary>PID: 9991312 | Type: read</summary>
				public const int fleprovisionedflowstablesourceip = 9991312;
				/// <summary>PID: 9991313 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablemetadata_9991313 = 9991313;
				/// <summary>PID: 9991313 | Type: read</summary>
				public const int fleprovisionedflowstablemetadata = 9991313;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableid_9991301 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleprovisionedflowstableid = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablesourceid_9991302 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleprovisionedflowstablesourceid = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationid_9991303 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationid = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableincomingdcfinterfaceid_9991304 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleprovisionedflowstableincomingdcfinterfaceid = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableincomingdcfinterfacedynamiclink_9991305 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleprovisionedflowstableincomingdcfinterfacedynamiclink = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoutgoingdcfinterfaceid_9991306 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleprovisionedflowstableoutgoingdcfinterfaceid = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoutgoingdcfinterfacedynamiclink_9991307 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleprovisionedflowstableoutgoingdcfinterfacedynamiclink = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoptionalsourceidentifier_9991308 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleprovisionedflowstableoptionalsourceidentifier = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstableoptionaldestinationidentifier_9991309 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleprovisionedflowstableoptionaldestinationidentifier = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationip_9991310 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationip = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstabledestinationport_9991311 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleprovisionedflowstabledestinationport = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablesourceip_9991312 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleprovisionedflowstablesourceip = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleprovisionedflowstablemetadata_9991313 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleprovisionedflowstablemetadata = 12;
			}
		}
	}
}
