// <auto-generated />
namespace Skyline.DataMiner.Scripting
{
	using System.ComponentModel;

	internal static class Parameter
	{
		/// <summary>PID: 9000000 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_receive_9000000 = 9000000;
		/// <summary>PID: 9000000 | Type: read</summary>
		public const int clp_interapp_receive = 9000000;
		/// <summary>PID: 9000001 | Type: read</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int clp_interapp_return_9000001 = 9000001;
		/// <summary>PID: 9000001 | Type: read</summary>
		public const int clp_interapp_return = 9000001;
		public class Write
		{
			/// <summary>PID: 1000158 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int fleincomingflowstableexpectedrxbitrate_1000158 = 1000158;
			/// <summary>PID: 1000158 | Type: write</summary>
			public const int fleincomingflowstableexpectedrxbitrate = 1000158;
			/// <summary>PID: 1000258 | Type: write</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int fleoutgoingflowstableexpectedtxbitrate_1000258 = 1000258;
			/// <summary>PID: 1000258 | Type: write</summary>
			public const int fleoutgoingflowstableexpectedtxbitrate = 1000258;
		}
		public class Fleinterfacesoverviewtable
		{
			/// <summary>PID: 1000000</summary>
			public const int tablePid = 1000000;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 1000001</summary>
			public const int indexColumnPid = 1000001;
			public class Pid
			{
				/// <summary>PID: 1000001 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableindex_1000001 = 1000001;
				/// <summary>PID: 1000001 | Type: read</summary>
				public const int fleinterfacesoverviewtableindex = 1000001;
				/// <summary>PID: 1000002 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledescription_1000002 = 1000002;
				/// <summary>PID: 1000002 | Type: read</summary>
				public const int fleinterfacesoverviewtabledescription = 1000002;
				/// <summary>PID: 1000003 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletype_1000003 = 1000003;
				/// <summary>PID: 1000003 | Type: read</summary>
				public const int fleinterfacesoverviewtabletype = 1000003;
				/// <summary>PID: 1000004 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableadminstatus_1000004 = 1000004;
				/// <summary>PID: 1000004 | Type: read</summary>
				public const int fleinterfacesoverviewtableadminstatus = 1000004;
				/// <summary>PID: 1000005 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableoperstatus_1000005 = 1000005;
				/// <summary>PID: 1000005 | Type: read</summary>
				public const int fleinterfacesoverviewtableoperstatus = 1000005;
				/// <summary>PID: 1000006 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledisplaykey_1000006 = 1000006;
				/// <summary>PID: 1000006 | Type: read</summary>
				public const int fleinterfacesoverviewtabledisplaykey = 1000006;
				/// <summary>PID: 1000007 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxbitrate_1000007 = 1000007;
				/// <summary>PID: 1000007 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxbitrate = 1000007;
				/// <summary>PID: 1000008 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxflows_1000008 = 1000008;
				/// <summary>PID: 1000008 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxflows = 1000008;
				/// <summary>PID: 1000009 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxbitrate_1000009 = 1000009;
				/// <summary>PID: 1000009 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxbitrate = 1000009;
				/// <summary>PID: 1000010 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxflows_1000010 = 1000010;
				/// <summary>PID: 1000010 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxflows = 1000010;
				/// <summary>PID: 1000011 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxutilization_1000011 = 1000011;
				/// <summary>PID: 1000011 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxutilization = 1000011;
				/// <summary>PID: 1000012 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxutilization_1000012 = 1000012;
				/// <summary>PID: 1000012 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxutilization = 1000012;
				/// <summary>PID: 1000013 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitrate_1000013 = 1000013;
				/// <summary>PID: 1000013 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitrate = 1000013;
				/// <summary>PID: 1000014 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus_1000014 = 1000014;
				/// <summary>PID: 1000014 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus = 1000014;
				/// <summary>PID: 1000015 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflows_1000015 = 1000015;
				/// <summary>PID: 1000015 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflows = 1000015;
				/// <summary>PID: 1000016 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus_1000016 = 1000016;
				/// <summary>PID: 1000016 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus = 1000016;
				/// <summary>PID: 1000017 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitrate_1000017 = 1000017;
				/// <summary>PID: 1000017 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitrate = 1000017;
				/// <summary>PID: 1000018 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus_1000018 = 1000018;
				/// <summary>PID: 1000018 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus = 1000018;
				/// <summary>PID: 1000019 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflows_1000019 = 1000019;
				/// <summary>PID: 1000019 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflows = 1000019;
				/// <summary>PID: 1000020 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus_1000020 = 1000020;
				/// <summary>PID: 1000020 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus = 1000020;
				/// <summary>PID: 1000021 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledcfinterfaceid_1000021 = 1000021;
				/// <summary>PID: 1000021 | Type: read</summary>
				public const int fleinterfacesoverviewtabledcfinterfaceid = 1000021;
				public class Write
				{
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableindex_1000001 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleinterfacesoverviewtableindex = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledescription_1000002 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleinterfacesoverviewtabledescription = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletype_1000003 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleinterfacesoverviewtabletype = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableadminstatus_1000004 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleinterfacesoverviewtableadminstatus = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableoperstatus_1000005 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleinterfacesoverviewtableoperstatus = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledisplaykey_1000006 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleinterfacesoverviewtabledisplaykey = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxbitrate_1000007 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxflows_1000008 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxflows = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxbitrate_1000009 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxbitrate = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxflows_1000010 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxflows = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtablerxutilization_1000011 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleinterfacesoverviewtablerxutilization = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabletxutilization_1000012 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleinterfacesoverviewtabletxutilization = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitrate_1000013 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitrate = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus_1000014 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxbitratestatus = 13;
				/// <summary>IDX: 14 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflows_1000015 = 14;
				/// <summary>IDX: 14 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflows = 14;
				/// <summary>IDX: 15 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus_1000016 = 15;
				/// <summary>IDX: 15 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedrxflowsstatus = 15;
				/// <summary>IDX: 16 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitrate_1000017 = 16;
				/// <summary>IDX: 16 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitrate = 16;
				/// <summary>IDX: 17 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus_1000018 = 17;
				/// <summary>IDX: 17 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxbitratestatus = 17;
				/// <summary>IDX: 18 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflows_1000019 = 18;
				/// <summary>IDX: 18 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflows = 18;
				/// <summary>IDX: 19 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus_1000020 = 19;
				/// <summary>IDX: 19 | Type: read</summary>
				public const int fleinterfacesoverviewtableexpectedtxflowsstatus = 19;
				/// <summary>IDX: 20 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleinterfacesoverviewtabledcfinterfaceid_1000021 = 20;
				/// <summary>IDX: 20 | Type: read</summary>
				public const int fleinterfacesoverviewtabledcfinterfaceid = 20;
			}
		}
		public class Fleincomingflowstable
		{
			/// <summary>PID: 1000100</summary>
			public const int tablePid = 1000100;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 1000101</summary>
			public const int indexColumnPid = 1000101;
			public class Pid
			{
				/// <summary>PID: 1000101 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableinstance_1000101 = 1000101;
				/// <summary>PID: 1000101 | Type: read</summary>
				public const int fleincomingflowstableinstance = 1000101;
				/// <summary>PID: 1000102 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationip_1000102 = 1000102;
				/// <summary>PID: 1000102 | Type: read</summary>
				public const int fleincomingflowstabledestinationip = 1000102;
				/// <summary>PID: 1000103 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationport_1000103 = 1000103;
				/// <summary>PID: 1000103 | Type: read</summary>
				public const int fleincomingflowstabledestinationport = 1000103;
				/// <summary>PID: 1000104 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablesourceip_1000104 = 1000104;
				/// <summary>PID: 1000104 | Type: read</summary>
				public const int fleincomingflowstablesourceip = 1000104;
				/// <summary>PID: 1000105 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableincominginterface_1000105 = 1000105;
				/// <summary>PID: 1000105 | Type: read</summary>
				public const int fleincomingflowstableincominginterface = 1000105;
				/// <summary>PID: 1000106 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabletransporttype_1000106 = 1000106;
				/// <summary>PID: 1000106 | Type: read</summary>
				public const int fleincomingflowstabletransporttype = 1000106;
				/// <summary>PID: 1000107 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablerxbitrate_1000107 = 1000107;
				/// <summary>PID: 1000107 | Type: read</summary>
				public const int fleincomingflowstablerxbitrate = 1000107;
				/// <summary>PID: 1000108 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitrate_1000108 = 1000108;
				/// <summary>PID: 1000108 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitrate = 1000108;
				/// <summary>PID: 1000109 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitratestatus_1000109 = 1000109;
				/// <summary>PID: 1000109 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitratestatus = 1000109;
				/// <summary>PID: 1000110 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelabel_1000110 = 1000110;
				/// <summary>PID: 1000110 | Type: read</summary>
				public const int fleincomingflowstablelabel = 1000110;
				/// <summary>PID: 1000111 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablefkoutgoing_1000111 = 1000111;
				/// <summary>PID: 1000111 | Type: read</summary>
				public const int fleincomingflowstablefkoutgoing = 1000111;
				/// <summary>PID: 1000112 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelinkedflow_1000112 = 1000112;
				/// <summary>PID: 1000112 | Type: read</summary>
				public const int fleincomingflowstablelinkedflow = 1000112;
				/// <summary>PID: 1000113 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableflowowner_1000113 = 1000113;
				/// <summary>PID: 1000113 | Type: read</summary>
				public const int fleincomingflowstableflowowner = 1000113;
				/// <summary>PID: 1000114 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablepresent_1000114 = 1000114;
				/// <summary>PID: 1000114 | Type: read</summary>
				public const int fleincomingflowstablepresent = 1000114;
				public class Write
				{
					/// <summary>PID: 1000165 | Type: write</summary>
					[EditorBrowsable(EditorBrowsableState.Never)]
					public const int fleincomingflowstabledelete_1000165 = 1000165;
					/// <summary>PID: 1000165 | Type: write</summary>
					public const int fleincomingflowstabledelete = 1000165;
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableinstance_1000101 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleincomingflowstableinstance = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationip_1000102 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleincomingflowstabledestinationip = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabledestinationport_1000103 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleincomingflowstabledestinationport = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablesourceip_1000104 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleincomingflowstablesourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableincominginterface_1000105 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleincomingflowstableincominginterface = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstabletransporttype_1000106 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleincomingflowstabletransporttype = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablerxbitrate_1000107 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleincomingflowstablerxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitrate_1000108 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitrate = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableexpectedrxbitratestatus_1000109 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleincomingflowstableexpectedrxbitratestatus = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelabel_1000110 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleincomingflowstablelabel = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablefkoutgoing_1000111 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleincomingflowstablefkoutgoing = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablelinkedflow_1000112 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleincomingflowstablelinkedflow = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstableflowowner_1000113 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleincomingflowstableflowowner = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleincomingflowstablepresent_1000114 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleincomingflowstablepresent = 13;
			}
		}
		public class Fleoutgoingflowstable
		{
			/// <summary>PID: 1000200</summary>
			public const int tablePid = 1000200;
			/// <summary>IDX: 0</summary>
			public const int indexColumn = 0;
			/// <summary>PID: 1000201</summary>
			public const int indexColumnPid = 1000201;
			public class Pid
			{
				/// <summary>PID: 1000201 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableinstance_1000201 = 1000201;
				/// <summary>PID: 1000201 | Type: read</summary>
				public const int fleoutgoingflowstableinstance = 1000201;
				/// <summary>PID: 1000202 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationip_1000202 = 1000202;
				/// <summary>PID: 1000202 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationip = 1000202;
				/// <summary>PID: 1000203 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationport_1000203 = 1000203;
				/// <summary>PID: 1000203 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationport = 1000203;
				/// <summary>PID: 1000204 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablesourceip_1000204 = 1000204;
				/// <summary>PID: 1000204 | Type: read</summary>
				public const int fleoutgoingflowstablesourceip = 1000204;
				/// <summary>PID: 1000205 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableoutgoinginterface_1000205 = 1000205;
				/// <summary>PID: 1000205 | Type: read</summary>
				public const int fleoutgoingflowstableoutgoinginterface = 1000205;
				/// <summary>PID: 1000206 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletransporttype_1000206 = 1000206;
				/// <summary>PID: 1000206 | Type: read</summary>
				public const int fleoutgoingflowstabletransporttype = 1000206;
				/// <summary>PID: 1000207 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletxbitrate_1000207 = 1000207;
				/// <summary>PID: 1000207 | Type: read</summary>
				public const int fleoutgoingflowstabletxbitrate = 1000207;
				/// <summary>PID: 1000208 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitrate_1000208 = 1000208;
				/// <summary>PID: 1000208 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitrate = 1000208;
				/// <summary>PID: 1000209 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitratestatus_1000209 = 1000209;
				/// <summary>PID: 1000209 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitratestatus = 1000209;
				/// <summary>PID: 1000210 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelabel_1000210 = 1000210;
				/// <summary>PID: 1000210 | Type: read</summary>
				public const int fleoutgoingflowstablelabel = 1000210;
				/// <summary>PID: 1000211 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablefkincoming_1000211 = 1000211;
				/// <summary>PID: 1000211 | Type: read</summary>
				public const int fleoutgoingflowstablefkincoming = 1000211;
				/// <summary>PID: 1000212 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelinkedflow_1000212 = 1000212;
				/// <summary>PID: 1000212 | Type: read</summary>
				public const int fleoutgoingflowstablelinkedflow = 1000212;
				/// <summary>PID: 1000213 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableflowowner_1000213 = 1000213;
				/// <summary>PID: 1000213 | Type: read</summary>
				public const int fleoutgoingflowstableflowowner = 1000213;
				/// <summary>PID: 1000214 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablepresent_1000214 = 1000214;
				/// <summary>PID: 1000214 | Type: read</summary>
				public const int fleoutgoingflowstablepresent = 1000214;
				public class Write
				{
					/// <summary>PID: 1000265 | Type: write</summary>
					[EditorBrowsable(EditorBrowsableState.Never)]
					public const int fleoutgoingflowstabledelete_1000265 = 1000265;
					/// <summary>PID: 1000265 | Type: write</summary>
					public const int fleoutgoingflowstabledelete = 1000265;
				}
			}
			public class Idx
			{
				/// <summary>IDX: 0 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableinstance_1000201 = 0;
				/// <summary>IDX: 0 | Type: read</summary>
				public const int fleoutgoingflowstableinstance = 0;
				/// <summary>IDX: 1 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationip_1000202 = 1;
				/// <summary>IDX: 1 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationip = 1;
				/// <summary>IDX: 2 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabledestinationport_1000203 = 2;
				/// <summary>IDX: 2 | Type: read</summary>
				public const int fleoutgoingflowstabledestinationport = 2;
				/// <summary>IDX: 3 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablesourceip_1000204 = 3;
				/// <summary>IDX: 3 | Type: read</summary>
				public const int fleoutgoingflowstablesourceip = 3;
				/// <summary>IDX: 4 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableoutgoinginterface_1000205 = 4;
				/// <summary>IDX: 4 | Type: read</summary>
				public const int fleoutgoingflowstableoutgoinginterface = 4;
				/// <summary>IDX: 5 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletransporttype_1000206 = 5;
				/// <summary>IDX: 5 | Type: read</summary>
				public const int fleoutgoingflowstabletransporttype = 5;
				/// <summary>IDX: 6 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstabletxbitrate_1000207 = 6;
				/// <summary>IDX: 6 | Type: read</summary>
				public const int fleoutgoingflowstabletxbitrate = 6;
				/// <summary>IDX: 7 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitrate_1000208 = 7;
				/// <summary>IDX: 7 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitrate = 7;
				/// <summary>IDX: 8 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableexpectedtxbitratestatus_1000209 = 8;
				/// <summary>IDX: 8 | Type: read</summary>
				public const int fleoutgoingflowstableexpectedtxbitratestatus = 8;
				/// <summary>IDX: 9 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelabel_1000210 = 9;
				/// <summary>IDX: 9 | Type: read</summary>
				public const int fleoutgoingflowstablelabel = 9;
				/// <summary>IDX: 10 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablefkincoming_1000211 = 10;
				/// <summary>IDX: 10 | Type: read</summary>
				public const int fleoutgoingflowstablefkincoming = 10;
				/// <summary>IDX: 11 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablelinkedflow_1000212 = 11;
				/// <summary>IDX: 11 | Type: read</summary>
				public const int fleoutgoingflowstablelinkedflow = 11;
				/// <summary>IDX: 12 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstableflowowner_1000213 = 12;
				/// <summary>IDX: 12 | Type: read</summary>
				public const int fleoutgoingflowstableflowowner = 12;
				/// <summary>IDX: 13 | Type: read</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int fleoutgoingflowstablepresent_1000214 = 13;
				/// <summary>IDX: 13 | Type: read</summary>
				public const int fleoutgoingflowstablepresent = 13;
			}
		}
	}
}
